version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
  calendar:
    build: .
    command: bash -c "cargo run"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://root:password@db/docker
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app/src

  # migrations:
  #   image: clux/diesel-cli
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     - DATABASE_URL=postgres://root:password@db/docker
  #   working_dir: /usr/src
  #   entrypoint: diesel migration run && diesel print-schema > src/schema.rs
  #   volumes:
  #     - ".:/usr/src"
  #   restart: "no"
