// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDate;
use crate::schema::*;
#[derive(Queryable, Debug, Identifiable)]
pub struct Birthday {
    pub id: i32,
    pub date: NaiveDate,
    pub person_id: Option<i32>,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(gift_id, giver_id)]
pub struct GiftGiver {
    pub gift_id: i32,
    pub giver_id: i32,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Gift {
    pub id: i32,
    pub name: String,
    pub price: Option<f32>,
    pub birthday_id: Option<i32>,
}

#[derive(Queryable, Debug, Identifiable)]
#[table_name = "parties"]
pub struct Party {
    pub id: i32,
    pub date: NaiveDate,
    pub host_id: Option<i32>,
    pub name: String,
    pub birthday_id: Option<i32>,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(party_id, guest_id)]
pub struct PartyGuest {
    pub party_id: i32,
    pub guest_id: i32,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Payment {
    pub id: i32,
    pub price: Option<f32>,
    pub vindicator_id: Option<i32>,
    pub vindicatee_id: Option<i32>,
    pub gift_id: Option<i32>,
    pub shopping_cart_id: Option<i32>,
}

#[derive(Queryable, Debug, Identifiable, AsChangeset, Serialize, Deserialize)]
pub struct Person {
    pub id: i32,
    pub name: String,
    pub bankaccount: Option<String>,
}

#[derive(Debug, Insertable, Serialize, Deserialize)]
#[table_name="persons"]
pub struct NewPerson {
    pub name: String,
    pub bankaccount: Option<String>,

}



#[derive(Queryable, Debug, Identifiable)]
#[primary_key(product_id, consumer_id)]
pub struct ProductConsumer {
    pub product_id: i32,
    pub consumer_id: i32,
}

#[derive(Queryable, Debug)]
pub struct Product {
    pub id: i32,
    pub price: Option<f32>,
    pub quantity: Option<i32>,
    pub shopping_cart_id: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct ShoppingCart {
    pub id: i32,
    pub owner_id: Option<i32>,
}
